In [1]:
# Libreria Datetime

from datetime import date, time, datetime

date(2020,12,25)


datetime.date(2020, 12, 25)

In [2]:
time(13,30,5)


datetime.time(13, 30, 5)

In [3]:
datetime(2020,12,25,13,30,5)

datetime.datetime(2020, 12, 25, 13, 30, 5)

In [4]:
print(datetime(2020,12,25,13,30,5))

2020-12-25 13:30:05


In [5]:
# Acceso a los componented de una fecha

from datetime import date,time,datetime

print(date.today())

2020-11-23


In [6]:
dt=datetime.now()
dt.year

2020

In [7]:
type(dt)

datetime.datetime

In [8]:
dt.month

11

In [9]:
dt.hour

21

In [10]:
dt.minute

39

In [11]:
dt.second

53

In [12]:
dt.microsecond

580372

In [14]:
# Conversión de fechas con cadenas con diferentes formatos

from datetime import date,time,datetime

d=datetime.now()
print(d.strftime("%d-%m-%Y"))

23-11-2020


In [16]:
print(d.strftime("%A,%d %B, %y"))

Monday,23 November, 20


In [18]:
print(d.strftime("%H: %M : %S"))

21: 44 : 38


In [19]:
print(d.strftime("%H horas, %M minutos y %S segundos"))

21 horas, 44 minutos y 38 segundos


In [21]:
# Conversión de cadenas en fechas

from datetime import date,time,datetime

datetime.strptime("23/11/2020","%d/%m/%Y")


datetime.datetime(2020, 11, 23, 0, 0)

In [22]:
datetime.strptime("2020-11-23 18:57:45","%Y-%m-%d %H:%M:%S")

datetime.datetime(2020, 11, 23, 18, 57, 45)

In [28]:
# Aritmética de fechas

from datetime import date,time,datetime,timedelta

d1=datetime(2020,1,1)
d1 + timedelta(31,3600)



datetime.datetime(2020, 2, 1, 1, 0)

In [30]:
datetime.now()- d1

datetime.timedelta(327, 79299, 710873)

In [40]:
# Libreria Numpy


# Array de una dimensión

import numpy as np

a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [35]:
# Array de dos dimensiones

a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [36]:
# Array de tres dimensiones

a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,1,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10  1 12]]]


In [46]:
# Otras funciones útiles que permiten generar arrays

import numpy as np

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [48]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [50]:
# Atributos de un array

a=np.array([[1,2,3],[4,5,6]])
print(a[1,0])

4


In [51]:
print(a[1][0])

4


In [52]:
print(a[:,0:2])

[[1 2]
 [4 5]]


In [54]:
# Filtrado de elementos de un array

a=np.array([[1,2,3],[4,5,6]])
print(a[(a %2==0)])

[2 4 6]


In [57]:
print(a[(a %2==0)&(a>2)])

[4 6]


In [58]:
# Operaciones matemáticas con arrays

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1,1],[2,2,2]])
print(a+b)

[[2 3 4]
 [6 7 8]]


In [59]:
print(a/b)

[[1.  2.  3. ]
 [2.  2.5 3. ]]


In [60]:
print(a**2)

[[ 1  4  9]
 [16 25 36]]


In [62]:
# Operaciones matemáticas a nivel de array

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1],[2,2],[3,3]])

print(a.dot(b))



[[14 14]
 [32 32]]


In [63]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [64]:
print(b.T)

[[1 2 3]
 [1 2 3]]
